(()=>{var c=["/","/offline","https://hugoinaction.github.io/GitHubPagesEnd/image/favicon_hue010d4fad590a87d325b7e07b2e61f59_2460_1e463977f25e99f95ee0709bc3be812b.png","https://hugoinaction.github.io/GitHubPagesEnd/logo.svg","https://hugoinaction.github.io/GitHubPagesEnd/background.svg","https://hugoinaction.github.io/GitHubPagesEnd/hero.svg","https://hugoinaction.github.io/GitHubPagesEnd/index.js","https://hugoinaction.github.io/GitHubPagesEnd/index.min.css","https://hugoinaction.github.io/GitHubPagesEnd/manifest.webmanifest"];(function(){let s="static",i="v1::";function h(){let e=c;return caches.open(i+s).then(t=>t.addAll(e)).catch(t=>{console.log("Error",t)})}self.addEventListener("activate",function(e){e.waitUntil(caches.keys().then(function(t){return Promise.all(t.filter(n=>n.indexOf(i)!==0).map(n=>caches.delete(n)))}))}),self.addEventListener("install",e=>e.waitUntil(h()));let o="/offline";function a(e=200){return caches.match(o).then(t=>t.text()).then(t=>new Response(t,{status:e,headers:{"Content-Type":"text/html"}}))}self.addEventListener("fetch",function(e){let t=e.request;if(t.method!=="GET")return e.respondWith(fetch(t).catch(()=>a(400)));if(t.headers.get("Accept").indexOf("text/html")!==-1||t.url.match(/\.(js|css)$/)){e.respondWith(fetch(t).then(function(n){let r=n.clone();return caches.open(i+s).then(function(u){u.put(t,r)}),n}).catch(function(){return caches.match(t).then(function(n){return n||(t.url.match(/\.(js|css)$/)?new Response(""):a(200))})}));return}e.respondWith(caches.match(t).then(function(n){return n||fetch(t).catch(function(){return t.url.match(/\.(jpe?g|png|gif|svg)$/)?new Response(`<svg role="img" aria-labelledby="offline" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
    <defs>
        <pattern id="textstripe" patternUnits="userSpaceOnUse" width="200" height="150" patternTransform="rotate(-45)">
            <text y="100" fill="rgba(0,0,0,0.33)" font-size="40">Offline</text>
        </pattern>
    </defs>
<rect width="100%" height="100%" fill="rgba(145,145,145,0.5)" stroke="rgba(0,0,0,0.33)" stroke-width="3"/>
<rect width="100%" height="100%" fill="url(#textstripe)" />
</svg>
`,{headers:{"Content-Type":"image/svg+xml"}}):new Response("")})}))})})();})();
